### ISSUE TITLE
totalSupply should be nat64

### ISSUE THREAD

**Issue by timohanke** [dfinity/ICRC-1#11]
https://github.com/dfinity/ICRC-1/blob/fd4cffe59b14e58570fd0ad6b85382998500ed7b/ICRC-1.did#L19

Probably a typo here. `balanceOf` returns nat64 so `totalSupply` can't be smaller than that.

That being said, `nat64` seems too small for both of them. You can't even map ETH (Wei units) to this type, let alone cycles. So we need nat128 or nat.

**Comment by MarioDfinity** [comment]
Thanks @timohanke, that was a bug that I fixed yesterday.
