### ISSUE TITLE
Issue with ICRC2_approve Method Assertion

### ISSUE THREAD

**Issue by wirapratamaz** [dfinity/ICRC-1#181]
I've encountered an issue with the ICRC2_approve method in the ICRC1.mo codebase. Specifically, I believe there is a potential problem with the assertion at line 529 in the code. Here's a summary of my concern:

When calling the ICRC2_approve method, I found myself trapped in the assertion at https://github.com/dfinity/ICRC1/blob/f4c51a7de774a243d7cfc6aee7c5261aed8dbc6e/ref/ICRC1.mo#L529

Upon further examination, it seems that this assertion might never pass because the condition balance(approverAccount, log) is unlikely to be equal to overflowOk(approverBalance - effectiveFee). For instance, if the balance is 1000, it's improbable for `balance(approverAccount, log)` to match `overflowOk(approverBalance - effectiveFee)`.

I'm reaching out to seek clarification or guidance on this matter. It's possible that I may be misunderstanding something, but I'm eager to resolve this issue. Any insights or assistance you can provide would be greatly appreciated.

**Comment by franRappazzini** [comment]
https://discord.com/channels/748416164832608337/748420568268800060/1220046895695790250

**Comment by wirapratamaz** [comment]
Great thank's someone already found it
