### ISSUE TITLE
SubAccount type is never technically specified

### ISSUE THREAD

**Issue by lastmjs** [dfinity/ICRC-1#25]
I would think that `SubAccount` should actually be a type in the standard. I imagine it is `type SubAccount = nat;` or something similar, but I'm not sure.

**Comment by di-wu** [comment]
A subaccount is an arbitrary 32-byte byte array.
```
type SubAccount = blob;
```

**Comment by lastmjs** [comment]
Fixed: https://github.com/dfinity/ICRC-1/pull/26
