### ISSUE TITLE
Deduplication from owner

### ISSUE THREAD

**Issue by lastmjs** [dfinity/ICRC-1#46]
Should deduplication take into account the from owner? You might have two transactions that look identical but are coming from two different owners. I think I just ran into this case with local testing.

**Comment by roman-kashitsyn** [comment]
> Should deduplication take into account the from owner? You might have two transactions that look identical but are coming from two different owners. I think I just ran into this case with local testing.

Yes, deduplication should take owner into account:

> If the ledger observed a structurally equal transfer payload (i.e., all the transfer argument fields **and the caller** have the same values) at transaction with index i, it should return `variant { Duplicate = record { duplicate_of = i } }`.
