### ISSUE TITLE
Assertion failing when using a canister's principal due to blob size requirement of 32

### ISSUE THREAD

**Issue by troublesprouter** [dfinity/ICRC-1#80]
https://github.com/dfinity/ICRC-1/blob/main/ref/Account.mo#L22

I'm using a canister's principal, size 10, as owner, and the assertion is failing because it requires a Principal of length 32.

Is this a bug? If not, what's going on?

**Comment by bytesun** [comment]
all AccountIdentifier is 32bits long in IC, you can refer to this example https://github.com/dfinity/examples/blob/master/motoko/ledger-transfer/src/ledger_transfer/Account.mo

**Comment by troublesprouter** [comment]
How do I process a principal to get it ready to use in the subaccount field of the argument passed on to

`Account.toText()` 

from https://github.com/dfinity/ICRC-1/blob/main/ref/Account.mo

**Comment by bytesun** [comment]
I guess you don't want to get specific subaccount, so just pass null for the "subaccount", then you get default account which index is 0.

**Comment by troublesprouter** [comment]
I need to pass a user's principal as subaccount, or more exactly, an adequate representation of it that is 32 bytes.

**Comment by bytesun** [comment]
I guess you want to build a Account using canister principal, right? then

let canister_account = { owner : <Canister Principal>; subaccount : null };

**Comment by troublesprouter** [comment]
No, I want to build one account per user, all owned by the canister.

Ideally 

let canister_owned_user_account = { owner : [canister principal]; subaccount : [user principal] };

but I realised that's not possible, due to principal size.

I'll just hash the user principal to force it into 32 bytes.

If there's a better, more direct way, I'd be interested.

**Comment by bytesun** [comment]
principal can't be subaccount, subaccount is the index of principal, so you can just assign the index to each user.

e.g. 
user1_account =   { owner : [canister principal]; subaccount :subToSubBlob(1)};
user2_account =   { owner : [canister principal]; subaccount :subToSubBlob(2)};
...

    public func subToSubBlob (sub : Nat) : Blob{
        let n_byte = func(i : Nat) : Nat8 {
            assert(i < 32);
            let shift : Nat = 8 * (32 - 1 - i);
            Nat8.fromIntWrap(sub / 2**shift)
        };
        Blob.fromArray(Array.tabulate<Nat8>(32, n_byte))
    };

**Comment by troublesprouter** [comment]
That adds a layer of complexity because you need another step mapping users to 1, 2, 3, etc.

I'll probably just hash the user's principal so that I can store the principal and not have to think about further mappings / open up opportunities for entanglement.

But thank you.
