### ISSUE TITLE
ICRC-2 Expiration Inconsistencies & long-term unused approval allowance build-up

### ISSUE THREAD

**Issue by levifeldman** [dfinity/ICRC-1#93]
Scenario: 

- At time t, principal-A calls icrc2_approve(spender: principal-B, amount: 10, expiration: t+4). 
- At time t+2, principal-A calls icrc2_approve(spender: principal-B, amount: 20, expiration: t+9).
- At time t+3, icrc2_allowance(account: principal-A, spender: principal-B) -> { allowance: 30; expires_at: t+9; }.
- At time t+5, icrc2_allowance(account: principal-A, spender: principal-B) -> { allowance: 30; expires_at: t+9; }.
- At time t+6, principal-B calls icrc2_transfer_from(from: principal-A, to: principal-B, amount: 17);
- At time t+7, icrc2_allowance(account: principal-A, spender: principal-B) -> { allowance: 13; expires_at: t+9; }.

In this scenario, the first approval made at time t never got transferred (because principal-B didn't need it, or principal-B's auction/sale sold-out/finished). Most of the second approval was transferred at time t+6. At time t+7, principal-B still has the allowance of the first approval even after the first approval's expiration-time of t+4.

Since most unused approval allowances will not be reset because there is a fee to lower an allowance or to reset an allowance to 0 and because why make the extra call and because most will expect the ledger to expire an approval allowance at the set expiration time, the above scenarios can add up in the long term where spenders have huge allowances from built-up unused approvals because the expirations carried over to the latest approvals. 

Possible Solutions:

a: Remove the expiration option from an approval. This will remove the expiration inconsistencies but is still susceptible to spenders building up huge allowances from unused approvals. 

b: Honor each approval's expiration by separating the allowances of each approval. To transfer_from an account, a spender must tell the ledger the block-height/id of the approval.

changes: 
```candid

type TransferFromArgs = record {
    from : Account;
    to : Account;
    // new field
    approval_id: nat;
    amount : nat;
    fee : opt nat;
    memo : opt blob;
    created_at_time : opt nat64;
};

type AllowanceArgs = record {
    account : Account;
    spender : principal;
    approval_id: nat; // new field
};

```
In the ledger: 
```rust
type ApprovalId = BlockHeight;

static APPROVALS: Map<(Account,Spender,ApprovalId), Approval>;

struct Approval {
    remaining_allowance: u64,
    expires_at: u64,
}
```

Let's go through the scenario above with this solution in place. 
 - At time t, principal-A calls icrc2_approve(spender: principal-B, amount: 10, expiration: t+4), the ledger adds a new entry in the APPROVALS map: APPROVALS.insert((principal-A-account, principal-B-spender, block_height_1), Approval { available_allowance: 10, expires_at: t+4 }).
 - At time t+2, principal-A calls icrc2_approve(spender: principal-B, amount: 20, expiration: t+9), the ledger adds a new entry in the APPROVALS map: APPROVALS.insert((principal-A-account, principal-B-spender, block_height_2), Approval { available_allowance: 20, expires_at: t+9 }).
 - At time t+3, icrc2_allowance(account: principal-A, spender: principal-B, approval_id: block_height_1) -> { allowance: 10; expires_at: t+4; }. icrc2_allowance(account: principal-A, spender: principal-B, approval_id: block_height_2) -> { allowance: 20; expires_at: t+9; }.
 - At time t+5, icrc2_allowance(account: principal-A, spender: principal-B, approval_id: block_height_1) -> { allowance: 0; expires_at: null; }. icrc2_allowance(account: principal-A, spender: principal-B, approval_id: block_height_2) -> { allowance: 20; expires_at: t+9; }.
 -  At time t+6, principal-B calls icrc2_transfer_from(approval_id: block_height_2, from: principal-A, to: principal-B, amount: 17); transfer_from success.
 -  At time t+7, icrc2_allowance(account: principal-A, spender: principal-B, approval_id: block_height_1) -> { allowance: 0; expires_at: null; }. icrc2_allowance(account: principal-A, spender: principal-B, approval_id: block_height_2) -> { allowance: 3; expires_at: t+9; }.

Separating each approval by its id, and requiring a spender to specify the approval-id when calling transfer_from, lets the ledger honor the expiration of an approval allowance, and stops a build-up of unused approval allowances.

**Comment by levifeldman** [comment]
Is solution-b the best way to stop a build-up of unused approval-allowances?
Within solution-b, Is it a good idea to have a maximum expiration time (30-days, 1-year, ...) on approvals?

**Comment by dietersommer** [comment]
Would a periodic "clean-up" action by the user (or her wallet) to reduce the superfluous approvals not be able to achieve the same, while keeping the much easier-to-implement expiration semantics?

**Comment by levifeldman** [comment]
https://github.com/dfinity/ICRC-1/pull/101

**Comment by levifeldman** [comment]
https://github.com/dfinity/ICRC-1/pull/109 solves for this scenario by overwriting the approval allowance with the approval amount in the call instead of adding onto it.
